### ISSUE TITLE
Code for calibration metrics using the subdistribution hazard method 

### ISSUE THREAD

**Issue by svd09** [survival-lumc/ValidationCompRisks#2]
Hi,

Thank you very much for the code and detailed explanation. The manuscript is superb. I am working on an external validation study and will be citing both the paper as well as your GitHub site.

Please provide the code for calibration metrics calculated using the sub distribution hazard approach by Austin et al. 
Thank you.

**Comment by danielegiardiello** [comment]
The R code to estimate the calibration measures using the subdistribution hazard approach has now been provided.

**Comment by svd09** [comment]
Thank you very much.

*Dr Salil V Deo MD*
Staff Cardiovascular Surgeon
Surgical Services, Louis Stokes Cleveland VAMC
North-east Ohio VA Healthcare
10701 East Boulevard
Cleveland Ohio 44106

Associate Professor
Department of Surgery
Case School of Medicine
Case Western Reserve University
Cleveland Ohio 44106
