### ISSUE TITLE
Variance of O/E measure

### ISSUE THREAD

**Issue by glyden** [survival-lumc/ValidationCompRisks#3]
Hello,

Thank you very much for sharing the code.

I believe there might be a small error in the CI calculation for the O/E measure:

https://github.com/survival-lumc/ValidationCompRisks/blob/152d2b7a0e1fdf932c4de35340d1a585d3abb240/Prediction_CSC_minimal.R#L233
https://github.com/survival-lumc/ValidationCompRisks/blob/152d2b7a0e1fdf932c4de35340d1a585d3abb240/Prediction_CSC_minimal.R#L234

The standard error used from the Debray paper seems to be the SE of log(O/E), in which case I believe the confidence intervals should be:
`"lower" = exp(log(OE) - qnorm(0.975) * aj$se / aj$obs)`
`"upper" = exp(log(OE) + qnorm(0.975) * aj$se / aj$obs)`

Thanks for considering my comment. I appreciate the thorough guide to this area!

**Comment by danielegiardiello** [comment]
Thank you very much to spot this issue. I modified the minimal code. I will modify the extended code accordingly.

**Comment by glyden** [comment]
Thank you for making the edit and for all the code!
